[project]
name = "geval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepeval>=3.7.2",
    "google-genai>=1.52.0",
    "ipykernel>=7.1.0",
    "openai>=2.8.1",
    "tqdm>=4.67.1",
]
